dist: xenial
before_install:
 - sudo add-apt-repository -y ppa:mike42/mdcheckr
 - sudo apt-get update
 - sudo apt-get -y install mdcheckr
script:
  - git ls-files | grep '\.md$' | tr '\n' '\0' | xargs -0 mdcheckr